server:
  port: 8080

spring:
  application:
    name: admin-delivery-user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/msa_delivery_admin_user?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: positive0302*
    pool:
      enabled: true
      initial-size: 50
      max-size: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
